In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/drive/MyDrive/train_news.csv')

In [3]:
df.head()

Unnamed: 0     id  ...                                               news label
0           0   9653  ...  WASHINGTON  —   In Sonny Perdue’s telling, Geo...     0
1           1  10041  ...  HOUSTON  —   Venezuela had a plan. It was a ta...     0
2           2  19113  ...  Sunday on ABC’s “This Week,” while discussing ...     0
3           3   6868  ...  AUGUSTA, Me.  —   The beleaguered Republican g...     0
4           4   7596  ...    Finian Cunningham has written extensively on...     1

[5 rows x 6 columns]

In [5]:
df.isnull().sum()

Unnamed: 0       0
id               0
headline       558
written_by    1957
news            39
label            0
dtype: int64

In [6]:
df=df.dropna()

In [8]:
#Get the independent features
X=df.drop(['label'],axis=1)
y=df['label']

In [9]:
#checking if the data is inbalance
y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [13]:
X.shape

(18285, 4)

In [12]:
X.drop(['Unnamed: 0'],axis=1,inplace=True)

In [11]:
import tensorflow as tf

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [16]:
#Vocabulary size
voc_size=5000

In [17]:
#One hot Representation
messages=X.copy()

In [18]:
messages['headline'][0]

'Ethics Questions Dogged Agriculture Nominee as Georgia Governor - The New York Times'

In [19]:
messages.reset_index(inplace=True)

In [20]:
import nltk
from nltk.corpus import stopwords
import re

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [26]:
#preprocessing
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',messages['headline'][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)


Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [27]:
corpus


['ethic question dog agricultur nomine georgia governor new york time',
 'u must dig deep stop argentina lionel messi new york time',
 'cotton hous walk plank vote bill cannot pass senat breitbart',
 'paul lepag besieg main governor send conflict signal intent new york time',
 'digit trump win',
 'rapid evolut save fish pollut studi say new york time',
 'alabama prison offici retali prison strike leader cut water cell',
 'live constant state love',
 'hillari closet drunk new wikileak email reveal aid ask sober day',
 'bloomberg back pennsylvania attorney gener sentenc month prison',
 'video le pen pelt egg keep smile',
 'donald trump candid american special interest',
 'wharton busi school backer seek distanc donald trump new york time',
 'brexit rule latest tactic block peopl',
 'million south korean rise shadow govern',
 'chelsea man ask obama cut sentenc time serv new york time',
 'citi vow fight trump immigr even lose million new york time',
 'youtub livestream pregnant giraff pull

In [28]:
onehot=[one_hot(words,voc_size)for words in corpus]
onehot

[[2443, 4983, 1108, 429, 2901, 3044, 2916, 605, 2015, 2004],
 [4238, 4738, 3260, 1775, 1488, 2002, 4717, 4679, 605, 2015, 2004],
 [183, 2825, 2109, 1476, 1895, 4587, 1945, 462, 3771, 1658],
 [2885, 3460, 4673, 2704, 2916, 1401, 4131, 4363, 2106, 605, 2015, 2004],
 [4052, 3573, 773],
 [1901, 2198, 1806, 25, 454, 2702, 2939, 605, 2015, 2004],
 [4295, 1570, 2630, 2202, 1570, 4139, 4609, 1481, 4809, 3005],
 [3450, 4806, 2772, 3867],
 [2276, 1609, 4643, 605, 738, 2448, 3085, 1620, 3508, 2446, 353],
 [506, 2565, 1586, 881, 4578, 4051, 1249, 1570],
 [4755, 4220, 4440, 1389, 2322, 1102, 188],
 [1425, 3573, 2684, 4856, 1723, 1015],
 [4165, 4978, 4803, 419, 4138, 3005, 1425, 3573, 605, 2015, 2004],
 [2699, 4132, 15, 170, 2739, 893],
 [929, 4926, 1907, 1337, 3474, 1447],
 [4328, 1968, 3508, 683, 1481, 4051, 2004, 1552, 605, 2015, 2004],
 [253, 2575, 1432, 3573, 3315, 3789, 319, 929, 605, 2015, 2004],
 [2123, 2483, 4708, 206, 2156, 1868, 1166, 2533, 1658],
 [394, 2321, 605, 2701, 3594, 605, 2015, 

In [31]:
#Embedding Representation
sent_length=20
embedded_docs=pad_sequences(onehot,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  605 2015 2004]
 [   0    0    0 ...  605 2015 2004]
 [   0    0    0 ...  462 3771 1658]
 ...
 [   0    0    0 ... 3432 2470 4635]
 [   0    0    0 ...  605 2015 2004]
 [   0    0    0 ... 1320 1620 1658]]


In [32]:
#creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [34]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,test_size=0.30,random_state=42)

In [39]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 14s 53ms/step - loss: 0.3187 - accuracy: 0.8469 - val_loss: 0.1859 - val_accuracy: 0.9247
Epoch 2/10
200/200 [==============================] - 10s 48ms/step - loss: 0.1465 - accuracy: 0.9445 - val_loss: 0.1935 - val_accuracy: 0.9211
Epoch 3/10
200/200 [==============================] - 10s 49ms/step - loss: 0.1048 - accuracy: 0.9621 - val_loss: 0.2060 - val_accuracy: 0.9185
Epoch 4/10
200/200 [==============================] - 10s 49ms/step - loss: 0.0757 - accuracy: 0.9730 - val_loss: 0.2459 - val_accuracy: 0.9174
Epoch 5/10
200/200 [==============================] - 10s 49ms/step - loss: 0.0510 - accuracy: 0.9823 - val_loss: 0.2592 - val_accuracy: 0.9185
Epoch 6/10
200/200 [==============================] - 10s 49ms/step - loss: 0.0342 - accuracy: 0.9883 - val_loss: 0.3451 - val_accuracy: 0.9156
Epoch 7/10
200/200 [==============================] - 10s 49ms/step - loss: 0.0212 - accuracy: 0.9929 - val_loss: 0.4155 - val_accuracy:

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [40]:

y_pred=model.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score