In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/train_news.csv')

In [ ]:
df.head()

Unnamed: 0     id  ...                                               news label
0           0   9653  ...  WASHINGTON  —   In Sonny Perdue’s telling, Geo...     0
1           1  10041  ...  HOUSTON  —   Venezuela had a plan. It was a ta...     0
2           2  19113  ...  Sunday on ABC’s “This Week,” while discussing ...     0
3           3   6868  ...  AUGUSTA, Me.  —   The beleaguered Republican g...     0
4           4   7596  ...    Finian Cunningham has written extensively on...     1

[5 rows x 6 columns]

In [ ]:
#checking missing value
df.isnull().sum()

Unnamed: 0       0
id               0
headline       558
written_by    1957
news            39
label            0
dtype: int64

In [ ]:
#droping nan values
df=df.dropna()

In [ ]:
#Get the independent features
X=df.drop(['label'],axis=1)

In [ ]:
#Getting dependent features
y=df['label']

In [ ]:
#Checking the shape
X.shape

(18285, 5)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
#Vocalabary size
voc_size=5000

In [ ]:
#OneHot Representation
messages=X.copy()

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#data setpreprocessing
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range (0,len(messages)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',messages['headline'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus ]
onehot_repr

[[3888, 214, 3093, 1191, 2154, 1879, 1791, 4577, 4663, 4023],
 [1386, 751, 4422, 2501, 2381, 171, 4778, 1006, 4577, 4663, 4023],
 [1586, 290, 3381, 1245, 3506, 3028, 83, 4010, 4938, 3228],
 [611, 1094, 4165, 859, 1791, 3781, 2899, 4961, 4957, 4577, 4663, 4023],
 [2957, 1705, 4871],
 [3470, 4121, 668, 1510, 1401, 4475, 854, 4577, 4663, 4023],
 [158, 695, 3380, 2951, 695, 1744, 145, 2530, 3374, 897],
 [795, 2717, 3151, 4937],
 [3870, 141, 3687, 4577, 2251, 1191, 1713, 1723, 546, 2026, 4317],
 [997, 2619, 571, 3584, 3128, 4991, 1836, 695],
 [3253, 1298, 3559, 3064, 2967, 1881, 184],
 [4120, 1705, 4681, 2335, 4473, 2209],
 [4835, 2941, 2652, 3410, 2834, 1525, 4120, 1705, 4577, 4663, 4023],
 [834, 2259, 3487, 4470, 4780, 763],
 [3930, 3412, 2085, 2787, 3201, 106],
 [257, 2279, 546, 1548, 2530, 4991, 4023, 1399, 4577, 4663, 4023],
 [2542, 70, 2994, 1705, 3508, 2685, 3979, 3930, 4577, 4663, 4023],
 [2895, 297, 1538, 550, 2194, 286, 2805, 461, 3228],
 [2877, 4735, 4577, 325, 3262, 4577, 4663, 

In [ ]:
corpus

['ethic question dog agricultur nomine georgia governor new york time',
 'u must dig deep stop argentina lionel messi new york time',
 'cotton hous walk plank vote bill cannot pass senat breitbart',
 'paul lepag besieg main governor send conflict signal intent new york time',
 'digit trump win',
 'rapid evolut save fish pollut studi say new york time',
 'alabama prison offici retali prison strike leader cut water cell',
 'live constant state love',
 'hillari closet drunk new wikileak email reveal aid ask sober day',
 'bloomberg back pennsylvania attorney gener sentenc month prison',
 'video le pen pelt egg keep smile',
 'donald trump candid american special interest',
 'wharton busi school backer seek distanc donald trump new york time',
 'brexit rule latest tactic block peopl',
 'million south korean rise shadow govern',
 'chelsea man ask obama cut sentenc time serv new york time',
 'citi vow fight trump immigr even lose million new york time',
 'youtub livestream pregnant giraff pull

In [ ]:
#Embedding Representation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4577 4663 4023]
 [   0    0    0 ... 4577 4663 4023]
 [   0    0    0 ... 4010 4938 3228]
 ...
 [   0    0    0 ... 4525 4703  491]
 [   0    0    0 ... 4577 4663 4023]
 [   0    0    0 ... 4071 1723 3228]]


In [ ]:
len(embedded_docs)

18285

In [ ]:
#creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
import numpy as np
X=np.array(embedded_docs)
y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.33,random_state=42)

In [ ]:
#Model training
model.fit(X_train,y_train,validation_data=(X_test,y_test,),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 10s 37ms/step - loss: 0.3367 - accuracy: 0.8418 - val_loss: 0.1867 - val_accuracy: 0.9206
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1390 - accuracy: 0.9455 - val_loss: 0.1842 - val_accuracy: 0.9264
Epoch 3/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1006 - accuracy: 0.9628 - val_loss: 0.2079 - val_accuracy: 0.9210
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0750 - accuracy: 0.9730 - val_loss: 0.2246 - val_accuracy: 0.9223
Epoch 5/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0521 - accuracy: 0.9821 - val_loss: 0.2790 - val_accuracy: 0.9109
Epoch 6/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0383 - accuracy: 0.9874 - val_loss: 0.2788 - val_accuracy: 0.9223
Epoch 7/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0225 - accuracy: 0.9931 - val_loss: 0.2962 - val_accuracy: 0.919

In [ ]:

from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [ ]:
y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix